//import images
import imageOne from '../images/Donne1.png';

const doneeInfo = [
    {
        dob : "1/1/2000",
        userId : "e6tw-hiu7-w8w8-32edwdo8",
        homeAddress : "charity street",
        country : "Nigeria",
        eduLevel : "Graduate",
        gender : "female",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to participate in a digital tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Jane Dov"
    },

    {
        dob : "1/1/2004",
        userId : "23dq-t-98yhe-98w98rh98",
        homeAddress : "Dorcas street",
        country : "Nigeria",
        eduLevel : "Graduate",
        gender : "female",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to participate in a digital tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Jacy Doe"
    },

    {
        dob : "1/1/2000",
        userId : "1238-ewi87-89yrw-w879ewo9309",
        homeAddress : "Man street",
        country : "Nigeria",
        eduLevel : "Graduate",
        gender : "female",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to participate in a digital tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Bella Doe"
    },
    {
        dob : "1/1/2002",
        userId : "1238-ewi87-89yrw-w879ewo9309",
        homeAddress : "Man street",
        country : "Nigeria",
        eduLevel : "UnderGraduate",
        gender : "female",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to participate in a digital tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Bella Doe"
    },
    {
        dob : "1/1/1999",
        userId : "1238-ewi87-89yrw-w879ewo9309",
        homeAddress : "Man street",
        country : "Nigeria",
        eduLevel : "UnderGraduate",
        gender : "male",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to participate in a digital tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Becky Doe"
    },
     {
        dob : "1/1/1989",
        userId : "1238-ewi87-89yrw-w879558uyt",
        homeAddress : "wesdate crescent street",
        country : "South Africa",
        eduLevel : "Researher",
        gender : "male",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to participate in a digital tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "James Dan"
    },
    {
        dob : "1/1/2002",
        userId : "1238-ewi87-89yrw-w879ewo9309",
        homeAddress : "Man street",
        country : "Nigeria",
        eduLevel : "UnderGraduate",
        gender : "female",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to participate in a digital tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Bella Doe"
    },
    {
        dob : "1/1/1999",
        userId : "1238-ewi87-89yrw-w879ewo9309",
        homeAddress : "Man street",
        country : "Nigeria",
        eduLevel : "Business man",
        gender : "Female",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to participate in a digital tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Becky Doe"
    },
    {
        dob : "1/1/1989",
        userId : "1238-ewi87-89yrw-w879558uyt",
        homeAddress : "wesdate crescent street",
        country : "South Africa",
        eduLevel : "Researher",
        gender : "male",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to participate in a digital tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "James Dan"
    },
    {
        dob : "1/1/1992",
        userId : "1238-ewi87-89yrw-w879558uyt",
        homeAddress : " Hatfield street",
        country : "South Africa",
        eduLevel : "Graduate",
        gender : "Female",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to participate in a digital tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Janet Lam"
    },
    {
        dob : "1/1/1990",
        userId : "1238-ewi87-89yrw-w879558uyt",
        homeAddress : " pictory street",
        country : "Egypt",
        eduLevel : "Graduate",
        gender : "Female",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to participate in a digital tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Fatma Isa"
    },
    {
        dob : "1/1/1991",
        userId : "1238-ewi87-89yrw-w879558uyt",
        homeAddress : " hamilton street",
        country : "Kenya",
        eduLevel : "UnderGraduate",
        gender : "Female",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to participate in a digital tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Dora Nyaro"
    },
    {
        dob : "1/1/1991",
        userId : "1238-ewi87-89yrw-w879558uyt",
        homeAddress : " yenne eric street",
        country : "Tunisia",
        eduLevel : "UnderGraduate",
        gender : "Female",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to participate in a digital tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "yalhai yetmu"
    },
    {
        dob : "1/1/1988",
        userId : "1238-ewi87-89yrw-w879558uyt",
        homeAddress : " redate street",
        country : "Kenya",
        eduLevel : "UnderGraduate",
        gender : "Female",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to participate in a digital tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "yeute yet"
    },
    {
        dob : "1/1/1996",
        userId : "1238-ewi87-89yrw-w879558uyt",
        homeAddress : " balaa street",
        country : "Ghana",
        eduLevel : "UnderGraduate",
        gender : "Female",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to participate in a digital tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "usana hassana"
    },
    {
        dob : "1/1/1986",
        userId : "1238-ewi87-89yrw-w8755tyrut",
        homeAddress : " White oaks street",
        country : "Egypt",
        eduLevel : "Graduate",
        gender : "Female",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to start my training as a project manager",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Safar Yunus"
    },
    {
        dob : "1/1/1990",
        userId : "1238-ewi87-89yrw-w879558dut",
        homeAddress : " Reservoir Hills",
        country : "South Africa",
        eduLevel : "Graduate",
        gender : "Female",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to participate in a digital tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Ziyabonga sli"
    },
    {
        dob : "1/1/1996",
        userId : "1238-ewi87-89yrw-w879558uyt",
        homeAddress : " Alekuwodo street",
        country : "Nigeria",
        eduLevel : "UnderGraduate",
        gender : "Male",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop for my online training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Damola Olagunju"
    },
    {
        dob : "1/1/2005",
        userId : "1238-ewi87-89yrw-w8783gjk98",
        homeAddress : " Raji Bayo Ayinde street",
        country : "Nigeria",
        eduLevel : "UnderGraduate",
        gender : "Female",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop for my online training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Damilola Anjuwon"
    },
    {
        dob : "1/1/1991",
        userId : "1238-ewi87-89yrw-w879558uyt",
        homeAddress : " maclarty ton street",
        country : "Kenya",
        eduLevel : "UnderGraduate",
        gender : "Female",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop to venture into digital marketing",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Doroben limbo"
    },
    {
        dob : "1/1/1988",
        userId : "1238-6798-89yrw-w879558uyt",
        homeAddress : " Beatrice street",
        country : "Ivory coast",
        eduLevel : "Graduate",
        gender : "Female",
        itemNeeded : "laptop",
        reasonForApplication : "I need a laptop for my tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Philiimonial Edet"
    },
    {
        dob : "1/1/1997",
        userId : "1238-ewi43-89yrw-w879558uyt",
        homeAddress : " wal street",
        country : "Ghana",
        eduLevel : "Graduate",
        gender : "male",
        itemNeeded : "phone",
        reasonForApplication : "I need a phone to participate in a digital tech training",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Ilyas Yusuf"
    },
    {
        dob : "1/1/1993",
        userId : "3218-ewi87-89yrw-w879558uyt",
        homeAddress : " hamilton street",
        country : "Kenya",
        eduLevel : "UnderGraduate",
        gender : "Female",
        itemNeeded : "phone",
        reasonForApplication : "I need a phone for the online trainning I'm doing.",
        imageLink : imageOne,
        letterOfRecomendationLink : imageOne,
        nationalIdLink: imageOne,
        orgName : "Tech4Dev",
        orgWebsite : "www.tech4dev.com",
        orgContact : "123-456-7890",
        signature : "Delphin Nyaroho"
    },
]

export default doneeInfo;