//import images
import imageOne from '../images/Donne1.png';

import ifunnanya from '../images/DoneeImages/Serah.png';
import hezron from '../images/DoneeImages/Hezron.png';
import reem from '../images/DoneeImages/Reem.png';
import fatma from '../images/DoneeImages/Sofia.png';
import joseph from '../images/DoneeImages/Joseph.png';
import yeute from '../images/DoneeImages/Aisha.png';
import lekan from '../images/DoneeImages/lekan.png';
import gloria from '../images/DoneeImages/Gloria.png';
import blessing from '../images/DoneeImages/Blessing.png';
import john from '../images/DoneeImages/John.png';
import Sally from '../../resources/images/Team/Sally.png';
import hammed from '../images/DoneeImages/Hamed.png';

const doneeInfo = [
    {
        firstName: "Ifunnanya",
        lastName: "Oke",
        dob: "1/1/1999",
        userId: "1238-ewi87-89yrw-w879ewo9309",
        homeAddress: "Man street",
        country: "Nigeria",
        phoneNumber: "010-100-200-300",
        eduLevel: "UnderGraduate",
        gender: "male",
        itemNeeded: "laptop",
        reasonForApplication: "I need a laptop to participate in a digital tech training",
        imageLink: ifunnanya,
        letterOfRecomendationLink: imageOne,
        nationalIdLink: imageOne,
        orgName: "Tech4Dev",
        orgWebsite: "www.tech4dev.com",
        orgContact: "123-456-7890",
        signature: "IfunnanyaOke"
    },

    {
        firstName: "Hezron",
        lastName: "Geteye",
        dob: "1/1/1989",
        userId: "1238-ewi87-89yrw-w879558uyt",
        homeAddress: "wesdate crescent street",
        country: "South Africa",
        phoneNumber: "010-100-200-300",
        eduLevel: "Researher",
        gender: "male",
        itemNeeded: "laptop",
        reasonForApplication: "I need a laptop to participate in a digital tech training",
        imageLink: hezron,
        letterOfRecomendationLink: imageOne,
        nationalIdLink: imageOne,
        orgName: "Tech4Dev",
        orgWebsite: "www.tech4dev.com",
        orgContact: "123-456-7890",
        signature: "HezronGeteye"
    },

    {
        firstName: "Reem",
        lastName: "Mohammed",
        dob: "1/1/1992",
        userId: "1238-ewi87-89yrw-w879558uyt",
        homeAddress: " Hatfield street",
        country: "Egypt",
        phoneNumber: "010-100-200-300",
        eduLevel: "Graduate",
        gender: "Female",
        itemNeeded: "laptop",
        reasonForApplication: "I need a laptop to participate in a digital tech training",
        imageLink: reem,
        letterOfRecomendationLink: imageOne,
        nationalIdLink: imageOne,
        orgName: "Tech4Dev",
        orgWebsite: "www.tech4dev.com",
        orgContact: "123-456-7890",
        signature: "ReemMohammed"
    },

    {
        firstName: "Fatma",
        lastName: "Isa",
        dob: "1/1/1990",
        userId: "1238-ewi87-89yrw-w879558uyt",
        homeAddress: " pictory street",
        country: "Egypt",
        phoneNumber: "010-100-200-300",
        eduLevel: "Graduate",
        gender: "Female",
        itemNeeded: "laptop",
        reasonForApplication: "I need a laptop to participate in a digital tech training",
        imageLink: fatma,
        letterOfRecomendationLink: imageOne,
        nationalIdLink: imageOne,
        orgName: "Tech4Dev",
        orgWebsite: "www.tech4dev.com",
        orgContact: "123-456-7890",
        signature: "FatmaIsa"
    },

    {
        firstName: "Joseph",
        lastName: "Munakin",
        dob: "1/1/1991",
        userId: "1238-ewi87-89yrw-w879558uyt",
        homeAddress: "hamilton street",
        country: "Kenya",
        phoneNumber: "010-100-200-300",
        eduLevel: "UnderGraduate",
        gender: "Female",
        itemNeeded: "laptop",
        reasonForApplication: "I need a laptop to participate in a digital tech training",
        imageLink: joseph,
        letterOfRecomendationLink: imageOne,
        nationalIdLink: imageOne,
        orgName: "Tech4Dev",
        orgWebsite: "www.tech4dev.com",
        orgContact: "123-456-7890",
        signature: "JOsephMunakin"
    },

    {
        firstName: "Yeute",
        lastName: "Yet",
        dob: "1/1/1988",
        userId: "1238-ewi87-89yrw-w879558uyt",
        homeAddress: " redate street",
        country: "Kenya",
        phoneNumber: "010-100-200-300",
        eduLevel: "UnderGraduate",
        gender: "Female",
        itemNeeded: "laptop",
        reasonForApplication: "I need a laptop to participate in a digital tech training",
        imageLink: yeute,
        letterOfRecomendationLink: imageOne,
        nationalIdLink: imageOne,
        orgName: "Tech4Dev",
        orgWebsite: "www.tech4dev.com",
        orgContact: "123-456-7890",
        signature: "yeuteyet"
    },
    {
        firstName: "Lekan",
        lastName: "Adediran",
        dob: "1/1/1996",
        userId: "1238-ewi87-89yrw-w879558uyt",
        homeAddress: " balaa street",
        country: "Nigeria",
        phoneNumber: "010-100-200-300",
        eduLevel: "UnderGraduate",
        gender: "Female",
        itemNeeded: "laptop",
        reasonForApplication: "I need a laptop to participate in a digital tech training",
        imageLink: lekan,
        letterOfRecomendationLink: imageOne,
        nationalIdLink: imageOne,
        orgName: "Tech4Dev",
        orgWebsite: "www.tech4dev.com",
        orgContact: "123-456-7890",
        signature: "LekanAdediran"
    },
    {
        firstName: "Gloria",
        lastName: "Kawasi",
        dob: "1/1/1986",
        userId: "1238-ewi87-89yrw-w8755tyrut",
        homeAddress: " White oaks street",
        country: "Ghana",
        phoneNumber: "010-100-200-300",
        eduLevel: "Graduate",
        gender: "Female",
        itemNeeded: "laptop",
        reasonForApplication: "I need a laptop to start my training as a project manager",
        imageLink: gloria,
        letterOfRecomendationLink: imageOne,
        nationalIdLink: imageOne,
        orgName: "Tech4Dev",
        orgWebsite: "www.tech4dev.com",
        orgContact: "123-456-7890",
        signature: "GloriaKawasi"
    },
    {
        firstName: "Blessing",
        lastName: "Ozor",
        dob: "1/1/1990",
        userId: "1238-ewi87-89yrw-w879558dut",
        homeAddress: " Reservoir Hills",
        country: "Nigeria",
        phoneNumber: "010-100-200-300",
        eduLevel: "Graduate",
        gender: "Female",
        itemNeeded: "laptop",
        reasonForApplication: "I need a laptop to participate in a digital tech training",
        imageLink: blessing,
        letterOfRecomendationLink: imageOne,
        nationalIdLink: imageOne,
        orgName: "Tech4Dev",
        orgWebsite: "www.tech4dev.com",
        orgContact: "123-456-7890",
        signature: "BlessingOzor"
    },

    {
        firstName: "Johanna",
        lastName: "Efua",
        dob: "1/1/1996",
        userId: "1238-ewi87-89yrw-w879558uyt",
        homeAddress: " Alekuwodo street",
        country: "Ghana",
        phoneNumber: "010-100-200-300",
        eduLevel: "UnderGraduate",
        gender: "Male",
        itemNeeded: "laptop",
        reasonForApplication: "I need a laptop for my online training",
        imageLink: imageOne,
        letterOfRecomendationLink: imageOne,
        nationalIdLink: john,
        orgName: "Tech4Dev",
        orgWebsite: "www.tech4dev.com",
        orgContact: "123-456-7890",
        signature: "John Efua"
    },

    {
        firstName: "Sally",
        lastName: "Xathi",
        dob: "1/1/1991",
        userId: "1238-ewi87-89yrw-w879558uyt",
        homeAddress: " maclarty ton street",
        country: "South Africa",
        phoneNumber: "010-100-200-300",
        eduLevel: "UnderGraduate",
        gender: "Female",
        itemNeeded: "laptop",
        reasonForApplication: "I need a laptop to venture into digital marketing",
        imageLink: Sally,
        letterOfRecomendationLink: imageOne,
        nationalIdLink: imageOne,
        orgName: "Tech4Dev",
        orgWebsite: "www.tech4dev.com",
        orgContact: "123-456-7890",
        signature: "SallyXathi"
    },

    {
        firstName: "Hammed",
        lastName: "Bashir",
        dob: "1/1/1997",
        userId: "1238-ewi43-89yrw-w879558uyt",
        homeAddress: " wal street",
        country: "Ghana",
        phoneNumber: "010-100-200-300",
        eduLevel: "Graduate",
        gender: "male",
        itemNeeded: "phone",
        reasonForApplication: "I need a phone to participate in a digital tech training",
        imageLink: hammed,
        letterOfRecomendationLink: imageOne,
        nationalIdLink: imageOne,
        orgName: "Tech4Dev",
        orgWebsite: "www.tech4dev.com",
        orgContact: "123-456-7890",
        signature: "HammedBashir"
    },
]

export default doneeInfo;